(()=>{
const VERSION='Beta 1.0';
const $=q=>document.querySelector(q);
const parse=(v,d)=>{try{return JSON.parse(v??'')??d}catch{return d}};
const toast=msg=>{let el=$('#betaToast');if(!el){el=document.createElement('div');el.id='betaToast';el.className='beta-toast';document.body.appendChild(el)}el.textContent=msg;el.classList.add('on');clearTimeout(window.__skioryToast);window.__skioryToast=setTimeout(()=>el.classList.remove('on'),2200)};
function getSavedLoc(){return parse(localStorage.getItem('cs3-loc'),null)}
function getMeta(){return parse(localStorage.getItem('skiory-location-meta'),null)}
function fmtAge(ts){if(!ts)return'';const m=Math.max(0,Math.round((Date.now()-ts)/60000));if(m<2)return'à l’instant';if(m<60)return`il y a ${m} min`;const h=Math.round(m/60);return`il y a ${h} h`}
function renderLocation(){const loc=getSavedLoc(),meta=getMeta(),title=$('#betaLocTitle'),status=$('#betaLocStatus'),btn=$('#betaLocate');if(!title||!status||!btn)return;if(loc?.lat&&loc?.lon){title.textContent='Position GPS active';status.textContent=`Distance et temps estimés activés pour les stations${meta?.ts?' · '+fmtAge(meta.ts):''}${meta?.accuracy?` · précision ~${Math.round(meta.accuracy)} m`:''}.`;btn.textContent='Actualiser';}else{title.textContent='Distances personnalisées';status.textContent='Active ta position pour afficher km et temps de trajet sur les stations.';btn.textContent='Activer le GPS';}}
function requestLocation(){const btn=$('#betaLocate'),status=$('#betaLocStatus');if(!navigator.geolocation){if(status)status.textContent='La géolocalisation n’est pas disponible sur ce navigateur.';return}if(btn){btn.disabled=true;btn.textContent='Localisation…'}if(status)status.textContent='Autorise Skiory à utiliser ta position pour calculer les distances.';navigator.geolocation.getCurrentPosition(pos=>{const loc={lat:pos.coords.latitude,lon:pos.coords.longitude};localStorage.setItem('cs3-loc',JSON.stringify(loc));localStorage.setItem('skiory-location-meta',JSON.stringify({accuracy:pos.coords.accuracy,ts:Date.now()}));if(status)status.textContent='Position enregistrée. Mise à jour des distances…';toast('Position GPS activée');setTimeout(()=>location.reload(),550)},err=>{if(btn){btn.disabled=false;btn.textContent='Réessayer'}if(status)status.textContent=err.code===1?'Accès à la position refusé. Tu peux l’autoriser dans les réglages du navigateur.':'Position indisponible pour le moment.'},{enableHighAccuracy:true,timeout:12000,maximumAge:30000})}
function reportText(){const visited=parse(localStorage.getItem('cs3-visited'),[]),sessions=parse(localStorage.getItem('cs3-sessions'),[]);return`Retour Skiory ${VERSION}\n\nCe que j’ai aimé :\n- \n\nCe qui pose problème :\n- \n\nIdée / amélioration :\n- \n\nDiagnostic : ${navigator.userAgent} · ${navigator.onLine?'en ligne':'hors ligne'} · ${visited.length} stations · ${sessions.length} sorties GPS`}
async function shareFeedback(){const text=reportText();try{if(navigator.share){await navigator.share({title:`Retour Skiory ${VERSION}`,text,url:location.href});return}await navigator.clipboard.writeText(text);toast('Modèle de retour copié')}catch(e){if(e?.name!=='AbortError')toast('Impossible de partager le retour')}}
async function copyDiagnostic(){try{await navigator.clipboard.writeText(reportText());toast('Diagnostic copié')}catch{toast('Copie indisponible')}}
function resetData(){if(!confirm('Réinitialiser les données Skiory de ce téléphone ? Favoris, collection, profils et sorties GPS seront effacés.'))return;const keys=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&(k.startsWith('cs2-')||k.startsWith('cs3-')||k.startsWith('skiory-')))keys.push(k)}keys.forEach(k=>localStorage.removeItem(k));toast('Données réinitialisées');setTimeout(()=>location.reload(),650)}
function init(){renderLocation();$('#betaLocate')?.addEventListener('click',requestLocation);$('#betaShare')?.addEventListener('click',shareFeedback);$('#betaDiag')?.addEventListener('click',copyDiagnostic);$('#betaReset')?.addEventListener('click',resetData);const v=$('#betaVersion');if(v)v.textContent=VERSION;if(getSavedLoc()&&navigator.permissions?.query){navigator.permissions.query({name:'geolocation'}).then(p=>{if(p.state==='granted'){navigator.geolocation.getCurrentPosition(pos=>{localStorage.setItem('cs3-loc',JSON.stringify({lat:pos.coords.latitude,lon:pos.coords.longitude}));localStorage.setItem('skiory-location-meta',JSON.stringify({accuracy:pos.coords.accuracy,ts:Date.now()}));renderLocation() },()=>{}, {enableHighAccuracy:false,timeout:5000,maximumAge:300000})}}).catch(()=>{})}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();